# Generated by Django 4.2.5 on 2023-10-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beatName', models.CharField(max_length=20)),
                ('beatBpm', models.IntegerField()),
                ('beatGenre', models.CharField(default='', max_length=20)),
                ('beatKey', models.CharField(max_length=10)),
                ('prodNickNames', models.CharField(max_length=30)),
                ('beatFile', models.FileField(default='', upload_to='audio/beats')),
                ('mp3LeasePrice', models.IntegerField()),
                ('wavLeasePrice', models.IntegerField()),
                ('trackoutLeasePrice', models.IntegerField()),
                ('unlimitedLeasePrice', models.IntegerField()),
                ('exclusiveLeasePrice', models.IntegerField()),
            ],
        ),
    ]
